name: wine_quality_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - pandas==2.1.4
      - numpy==1.26.2
      - scikit-learn==1.3.2
      - mlflow==2.19.0
      - dagshub==0.3.12
      - matplotlib==3.8.2
      - seaborn==0.13.0
      - joblib==1.3.2
